# try_except_err.py